// GatePlus Seed Data - CS Subjects, Topics, Weightage

export const BRANCHES = [
  { code: 'CS', name: 'Computer Science & IT', short: 'Computer Science' },
  { code: 'DA', name: 'Data Science & AI', short: 'Data Science & AI' },
  { code: 'ECE', name: 'Electronics & Communication', short: 'Electronics' },
  { code: 'EE', name: 'Electrical Engineering', short: 'Electrical' },
  { code: 'ME', name: 'Mechanical Engineering', short: 'Mechanical' },
  { code: 'CE', name: 'Civil Engineering', short: 'Civil' },
];

export const TARGET_DATES = {
  2026: '2026-02-07',
  2027: '2027-02-06',
  2028: '2028-02-05',
};

// CS Subject weightage (sorted by avg marks high to low)
export const CS_SUBJECTS = [
  { key: 'aptitude', name: 'Aptitude & English (General Aptitude)', avgMarks: 15, range: '15', weightage: 15, difficulty: 'Easy' },
  { key: 'math', name: 'Engineering Mathematics', avgMarks: 13, range: '11–15', weightage: 13, difficulty: 'Moderate' },
  { key: 'algorithms', name: 'Algorithms', avgMarks: 9, range: '7–11', weightage: 9, difficulty: 'Hard' },
  { key: 'ds', name: 'Data Structures & C Programming', avgMarks: 9, range: '7–11', weightage: 9, difficulty: 'Moderate' },
  { key: 'os', name: 'Operating Systems', avgMarks: 9, range: '7–11', weightage: 9, difficulty: 'Moderate' },
  { key: 'cn', name: 'Computer Networks', avgMarks: 8, range: '6–10', weightage: 8, difficulty: 'Moderate' },
  { key: 'dbms', name: 'DBMS', avgMarks: 8, range: '6–10', weightage: 8, difficulty: 'Moderate' },
  { key: 'coa', name: 'Computer Organization & Architecture', avgMarks: 8, range: '6–10', weightage: 8, difficulty: 'Moderate' },
  { key: 'discrete', name: 'Discrete Mathematics', avgMarks: 8, range: '6–10', weightage: 8, difficulty: 'Moderate' },
  { key: 'cd', name: 'Compiler Design', avgMarks: 7, range: '5–9', weightage: 7, difficulty: 'Moderate' },
  { key: 'toc', name: 'Theory of Computation', avgMarks: 7, range: '5–9', weightage: 7, difficulty: 'Hard' },
  { key: 'dl', name: 'Digital Logic', avgMarks: 6, range: '4–8', weightage: 6, difficulty: 'Moderate' },
];

// CS Topics - 159 topics total
export const CS_TOPICS = {
  math: [
    'Probability — conditional & Bayes|HIGH',
    'Probability distributions|HIGH',
    'Linear Algebra — eigenvalues & eigenvectors|HIGH',
    'Linear Algebra — rank & systems of equations|HIGH',
    'Calculus — limits & continuity|HIGH',
    'Calculus — maxima & minima|HIGH',
    'Calculus — integration|HIGH',
    'Combinatorics & counting|HIGH',
    'Graph Theory — degree & connectivity|HIGH',
    'Graph Theory — trees|HIGH',
    'Set theory basics|LOW',
    'Numerical methods|LOW',
    'Transform theory|LOW',
    'Differential equations|LOW',
    'Complex analysis|LOW',
  ],
  discrete: [
    'Mathematical logic|HIGH',
    'Predicate logic|HIGH',
    'Sets & relations|HIGH',
    'Functions|HIGH',
    'Graph theory — Euler & Hamiltonian|HIGH',
    'Graph theory — coloring|HIGH',
    'Combinatorics — PIE|HIGH',
    'Recurrence relations|HIGH',
    'Generating functions|HIGH',
    'Lattices|LOW',
    'Posets|LOW',
    'Boolean algebra|LOW',
  ],
  algorithms: [
    'Asymptotic analysis (Big-O, Θ, Ω)|HIGH',
    'Recurrences & Master theorem|HIGH',
    'Greedy — Huffman coding|HIGH',
    "MST — Prim's algorithm|HIGH",
    "MST — Kruskal's algorithm|HIGH",
    'DP — Longest Common Subsequence|HIGH',
    'DP — Matrix Chain Multiplication|HIGH',
    'DP — 0/1 Knapsack|HIGH',
    'Divide & conquer — sorting|HIGH',
    'Divide & conquer — searching|HIGH',
    'Graph — BFS|HIGH',
    'Graph — DFS|HIGH',
    'Graph — Dijkstra|HIGH',
    'Graph — Bellman-Ford|HIGH',
    'Graph — Floyd-Warshall|HIGH',
    'Sorting algorithms|HIGH',
    'NP-completeness|LOW',
    'Approximation algorithms|LOW',
  ],
  ds: [
    'Arrays and strings|HIGH',
    'Linked lists|HIGH',
    'Stacks and queues|HIGH',
    'Trees — BST, AVL|HIGH',
    'Trees — B-trees|HIGH',
    'Heaps and priority queues|HIGH',
    'Hashing|HIGH',
    'Graphs — representation|HIGH',
    'C programming basics|HIGH',
    'C pointers and memory|HIGH',
    'C file I/O|LOW',
    'C preprocessor|LOW',
    'Recursion|HIGH',
    'Sorting in DS context|HIGH',
    'Tries|LOW',
    'Segment trees|LOW',
  ],
  os: [
    'Process management|HIGH',
    'Scheduling — FCFS|HIGH',
    'Scheduling — SJF|HIGH',
    'Scheduling — Round Robin|HIGH',
    'Scheduling — Priority|HIGH',
    'Synchronization — semaphores|HIGH',
    'Synchronization — monitors|HIGH',
    'Deadlocks — detection|HIGH',
    'Deadlocks — prevention|HIGH',
    'Memory — paging|HIGH',
    'Memory — segmentation|HIGH',
    'Virtual memory — page replacement|HIGH',
    'File systems|HIGH',
    'Disk scheduling|LOW',
    'I/O management|LOW',
    'Protection and security|LOW',
    'Linux basics|LOW',
  ],
  dbms: [
    'ER model and schema design|HIGH',
    'Relational algebra|HIGH',
    'SQL — basic queries|HIGH',
    'SQL — joins|HIGH',
    'Normalization — 1NF to BCNF|HIGH',
    'Transactions — ACID|HIGH',
    'Concurrency control|HIGH',
    'Indexing — B+ trees|HIGH',
    'Query optimization|HIGH',
    'Recovery techniques|LOW',
    'NoSQL basics|LOW',
    'Stored procedures|LOW',
  ],
  cn: [
    'OSI and TCP/IP model|HIGH',
    'Data link — framing, error detection|HIGH',
    'MAC protocols|HIGH',
    'Sliding window — Go-Back-N|HIGH',
    'Sliding window — Selective Repeat|HIGH',
    'IP addressing and subnetting|HIGH',
    'Routing protocols|HIGH',
    'Transport — TCP vs UDP|HIGH',
  ],
  toc: [
    'DFA and NFA|HIGH',
    'Regular expressions|HIGH',
    'Context-free grammars|HIGH',
    'Pushdown automata|HIGH',
    'Turing machines|HIGH',
    'Decidability|HIGH',
    'Complexity classes|HIGH',
  ],
  cd: [
    'Lexical analysis|HIGH',
    'Parsing — LL(1)|HIGH',
    'Parsing — LR, SLR, LALR|HIGH',
    'Syntax-directed definitions|HIGH',
    'Intermediate code generation|HIGH',
    'Code optimization|LOW',
    'Code generation|LOW',
  ],
  dl: [
    'Boolean algebra and minimization|HIGH',
    'Combinational circuits|HIGH',
    'Sequential circuits — flip-flops|HIGH',
    'Counters and registers|HIGH',
    'Number systems and arithmetic|HIGH',
    'Memory and programmable logic|LOW',
  ],
  coa: [
    'Machine instructions and addressing|HIGH',
    'ALU design|HIGH',
    'Control unit design|HIGH',
    'Pipelining|HIGH',
    'Cache memory|HIGH',
    'Memory hierarchy|HIGH',
    'I/O organization|LOW',
    'Instruction level parallelism|LOW',
  ],
  aptitude: [
    'Quant — ratios & percentages|HIGH',
    'Quant — time, speed & distance|HIGH',
    'Quant — work & time|HIGH',
    'Quant — profit & loss|HIGH',
    'Quant — number systems|HIGH',
    'Quant — permutation & combination|HIGH',
    'Quant — probability basics|HIGH',
    'Quant — geometry & mensuration|HIGH',
    'Verbal — sentence completion|HIGH',
    'Verbal — reading comprehension|HIGH',
    'Verbal — grammar|HIGH',
    'Logical — syllogisms|HIGH',
    'Logical — blood relations|HIGH',
    'Logical — coding-decoding|HIGH',
    'Logical — data interpretation|HIGH',
  ],
};

// Build flat topic list with IDs
export function getAllCSTopics() {
  const out = [];
  CS_SUBJECTS.forEach((sub) => {
    const topics = CS_TOPICS[sub.key] || [];
    topics.forEach((t, i) => {
      const [name, priority] = t.split('|');
      out.push({
        id: `${sub.key}:${i}`,
        subjectKey: sub.key,
        subject: sub.name,
        name,
        priority,
        avgMarks: sub.avgMarks,
        weightage: sub.weightage,
      });
    });
  });
  return out;
}

export const TOTAL_CS_TOPICS = getAllCSTopics().length;
